when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker.io/node:20
    commands:
      - npm ci
      - npm run build
      - cp -TR build /tmp/output
    volumes:
      - /srv/memeboard:/tmp/output